### ISSUE TITLE
Inactive "install selected mod" button

### ISSUE THREAD

**Issue by olibeniron** [Sehyn/wuwa_modloader#1]
Hi! Thank you for making the mod manager.
I downloaded it and directed a path, but the button to install the mods doesn't light up. The window is also... strangely small and I can't enlarge it.
![Снимок экрана 2024-06-08 210958](https://github.com/Sehyn/wuwa_modloader/assets/48998606/53a19160-371e-4fdf-a7c1-4763558486e6)

**Comment by Sehyn** [comment]
Interesting, do you use a different screen scaling ? Like you're on a 4K monitor but you're 125% on windows settings?

Fixed here: https://github.com/Sehyn/wuwa_modloader/releases/tag/1.0.1

**Comment by olibeniron** [comment]
No, both my monitors are at the standart 1920x1080 and 100% scaling.
Thanks, I'll try it now.

**Comment by olibeniron** [comment]
Yeah, the button works now, and the mods seem to be working to. I have yet to check them all, though some I just... prefer no to take such risks. I've tested antianticheat, antidither, multihitx15, perceptionrange and plotcanskip, all work.
Thank you!
