### ISSUE TITLE
Gktwo nuked his repo

### ISSUE THREAD

**Issue by angousana** [Sehyn/wuwa_modloader#3]
Anyone made a fork of https://github.com/Gktwo/KUN-mod ?

**Comment by Sehyn** [comment]
Yea I did will post tomorrow

**Comment by conongnang** [comment]
@Sehyn @angousana is this mod still work in 1,1?

**Comment by SDUBZ** [comment]
> @Sehyn @angousana is this mod still work in 1,1?

doesn't too gets to loading screen and doesnt show anything once at login it part where you usually choose players ect

**Comment by WoooJenkies** [comment]
Devs have obviously changed some blueprint stuff in 1.1 so the Kun mods don't work anymore.

Until someone gets the AES key and finds out where the new variables for things are, you will be waiting no doubt, unless someone was to go learn how to unpack unreal pak files and then make their own paks. Pak11 is usually the one with all the goodies.

**Comment by SDUBZ** [comment]
There was a post I saw with aes key wuwa mod blueprint shows 1.1 keys

**Comment by SDUBZ** [comment]
> Yea I did will post tomorrow

if you are interested or anyone here with some knowledge this is a great place to start https://github.com/aarlin/wuthering-waves-mod-starter
